### ISSUE TITLE
project examples also using qt designer forms and widgets?

### ISSUE THREAD

**Issue by dsyleixa** [StefanFrings/QtWebApp#1]
hello,
would it be possible to provide also some apps using qt designer forms and widgets by drag+drop?
Target: Running on a Raspberry Pi as a normal Linux executable (no demon).
e.g.,  a text box for displaying event messages of the running program (like Arduino Serial monitor)  plus a quit button

then designing a html web form (static local IP) for programs like:
- 2 buttons to switch a local Raspi LED on/off
- dto., plus login/pwd  authorization before showing up the website
- dto, plus a chart table  to show local Raspi DHT22 sensor readings
- dto, to connect to a remote esp8266, and 2 buttons  to switch an esp8266 remote LED on/off 
(ESP code: by Arduino IDE)
- dto, plus a chart table  to show remote (esp8266) DHT22 and/or GPIO switch sensor readings

(actions or events on the website monitored also in the qt app text box)

**Comment by StefanFrings** [comment]
This question is not related to QtWebApp. This is the wrong place to ask such questions.
